import { GlobalStyle } from "@/styles/globalStyle";
import StyledComponentsRegistry from "./registry";
import Header from "@/components/header";
import { Box, Container } from "@/styles/styles";
import NavBar from "@/components/navBar";

export const metadata = {
  title: "Movieing Box",
  description: "Generated by Yeseul",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyle />
          <Container>
            <Header />
            <Box>
              <NavBar />
              {children}
            </Box>
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
