import { GlobalStyle } from "@/styles/globalStyle";
import StyledComponentsRegistry from "./registry";
import Header from "@/components/header";
import { Container } from "@/styles/styles";

export const metadata = {
  title: "Movieing Box",
  description: "Generated by Yeseul",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <StyledComponentsRegistry>
          <Container>
            <GlobalStyle />
            <Header />
            {children}
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
